### ISSUE TITLE
containers.istio.tetratelabs.com not resolvable

### ISSUE THREAD

**Issue by zeemy23** [tetratelabs/helm-charts#6]
Hello, our container pulls started failing from containers.istio.tetratelabs.com today. it looks like you're missing a cname entry because docker-prd-arz0zuhgi0bq.cloudsmith.io still works.

**Comment by zeemy23** [comment]
cc @dussab

**Comment by boeboe** [comment]
Thanks for letting us know @zeemy23 . The issue is currently being looked at.

**Comment by liamawhite** [comment]
This should now be resolved. Please let us know if you are still having issues (pending DNS TTL, etc.).
